repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.88.4 # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
    hooks:
      - id: terraform_fmt
        args:
          - --args=--recursive
      - id: terraform_tflint
        args:
          - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl
          - --args=--module
          - --args=--enable-rule=terraform_deprecated_interpolation
          - --args=--enable-rule=terraform_deprecated_index
          - --args=--enable-rule=terraform_comment_syntax
          - --args=--enable-rule=terraform_documented_outputs
          - --args=--enable-rule=terraform_documented_variables
          - --args=--enable-rule=terraform_typed_variables
          - --args=--enable-rule=terraform_module_pinned_source
          - --args=--enable-rule=terraform_naming_convention
          - --args=--enable-rule=terraform_required_version
          - --args=--enable-rule=terraform_required_providers
          - --args=--enable-rule=terraform_standard_module_structure
      - id: terraform_tfsec
     # - id: terraform_trivy
      - id: terraform_docs
        args:
          - --args=--config=.tf-docs.yml


  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      # git checks
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: no-commit-to-branch
      # Additional File types
      - id: check-yaml
      - id: check-json
      # Common file checks
      - id: mixed-line-ending
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
        exclude: CHANGELOG.md|README.md
