formatter: "markdown table" # this is required
version: "0.17"
header-from: main.tf
#footer-from: ""
recursive:
  enabled: false
  path: ""

sections:
  hide: []
  show: []

content: |-
  {{ .Header }}

  {{ .Requirements }}

  ## Usage
  Basic usage of this module is as follows:
  ```hcl
    module "example" {
      {{"\t"}} source  = "<path-to-module>"

    {{- if .Module.RequiredInputs }}
          {{"\n\t"}} # Required variables
          {{- range .Module.RequiredInputs }}
          {{"\t"}} {{ .Name }}  = "{{ .GetValue }}"
          {{- end }}
          {{- end }}
  }
  ```

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}

output:
  file: README.md
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}

    <!-- END_TF_DOCS -->

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: true
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
